/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ser.jint.javainterui.gui;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import ser.jint.bo.Order;
import ser.jint.facade.OrderFacadeSubject;
import ser.jint.javainterui.datamodels.OrderDataModel;
import ser.jint.strategy.ListingStrategy;
import ser.jint.strategy.OrderDateListing;
import ser.jint.strategy.OrderIdListing;
import ser.jint.strategy.OrderStateListing;
import ser.jint.wizardmodels.CreateOrder;

/**
 *
 * @author Razorback
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        centrarPantalla();
        initOrderTable();
    }

    private void centrarPantalla() {
        Dimension tamFrame = this.getSize();//para obtener las dimensiones del frame
        Dimension tamPantalla = Toolkit.getDefaultToolkit().getScreenSize();//para obtener el tamaño de la pantalla
        setLocation((tamPantalla.width - tamFrame.width) / 2, (tamPantalla.height - tamFrame.height) / 2);//para posicionar
    }

    private void initOrderTable() {
        OrderDataModel dataModel = new OrderDataModel(OrderFacadeSubject.getInstance().getOrderList());
        
        System.out.println("Size: " + OrderFacadeSubject.getInstance().getOrderList().size());
        
        this.tblOrders.setModel(dataModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupRadFind = new javax.swing.ButtonGroup();
        btnGroupRadOrder = new javax.swing.ButtonGroup();
        pnlTasks = new javax.swing.JPanel();
        btnCargarDatos = new javax.swing.JButton();
        btnGuardarDatos = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        pnlFooter = new javax.swing.JPanel();
        pnlFunctions = new javax.swing.JPanel();
        pnlOrderFind = new javax.swing.JPanel();
        lblCampoBusqueda = new javax.swing.JLabel();
        txtCampoBusqueda = new javax.swing.JTextField();
        radFindNroCliente = new javax.swing.JRadioButton();
        radFindNroOrden = new javax.swing.JRadioButton();
        pnlEstadoOrden = new javax.swing.JPanel();
        cmbDispatcher = new javax.swing.JComboBox();
        radFindState = new javax.swing.JRadioButton();
        btnFindOrder = new javax.swing.JButton();
        pnlOrderListCriteria = new javax.swing.JPanel();
        radCriteriaNroOrden = new javax.swing.JRadioButton();
        radCriteriaEstadoOrden = new javax.swing.JRadioButton();
        radCriteriaFechaCreacion = new javax.swing.JRadioButton();
        pnlHigherFunctions = new javax.swing.JPanel();
        btnNuevaOrden = new javax.swing.JButton();
        btnAbmItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrders = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion Pedidos");
        setResizable(false);

        btnCargarDatos.setText("Cargar Datos");
        btnCargarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarDatosActionPerformed(evt);
            }
        });

        btnGuardarDatos.setText("Guardar Datos");
        btnGuardarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDatosActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refrescar");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTasksLayout = new javax.swing.GroupLayout(pnlTasks);
        pnlTasks.setLayout(pnlTasksLayout);
        pnlTasksLayout.setHorizontalGroup(
            pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCargarDatos)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarDatos)
                .addGap(18, 18, 18)
                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(806, Short.MAX_VALUE))
        );
        pnlTasksLayout.setVerticalGroup(
            pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTasksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCargarDatos)
                    .addComponent(btnGuardarDatos)
                    .addComponent(btnRefresh))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        getContentPane().add(pnlTasks, java.awt.BorderLayout.PAGE_START);

        javax.swing.GroupLayout pnlFooterLayout = new javax.swing.GroupLayout(pnlFooter);
        pnlFooter.setLayout(pnlFooterLayout);
        pnlFooterLayout.setHorizontalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1155, Short.MAX_VALUE)
        );
        pnlFooterLayout.setVerticalGroup(
            pnlFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        getContentPane().add(pnlFooter, java.awt.BorderLayout.PAGE_END);

        pnlFunctions.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        pnlOrderFind.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar Orden"));

        lblCampoBusqueda.setText("Campo Busqueda");

        btnGroupRadFind.add(radFindNroCliente);
        radFindNroCliente.setSelected(true);
        radFindNroCliente.setText("Nro Cliente");

        btnGroupRadFind.add(radFindNroOrden);
        radFindNroOrden.setText("Nro Orden");

        pnlEstadoOrden.setBorder(javax.swing.BorderFactory.createTitledBorder("LugarDespachado"));

        cmbDispatcher.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "UPS", "FedEx", "Correo Argentino", "OCA", "Andreani", "Ocasa", "Western Union" }));

        btnGroupRadFind.add(radFindState);

        javax.swing.GroupLayout pnlEstadoOrdenLayout = new javax.swing.GroupLayout(pnlEstadoOrden);
        pnlEstadoOrden.setLayout(pnlEstadoOrdenLayout);
        pnlEstadoOrdenLayout.setHorizontalGroup(
            pnlEstadoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEstadoOrdenLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radFindState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cmbDispatcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlEstadoOrdenLayout.setVerticalGroup(
            pnlEstadoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEstadoOrdenLayout.createSequentialGroup()
                .addGroup(pnlEstadoOrdenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDispatcher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radFindState))
                .addGap(0, 3, Short.MAX_VALUE))
        );

        btnFindOrder.setText("Buscar");
        btnFindOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlOrderFindLayout = new javax.swing.GroupLayout(pnlOrderFind);
        pnlOrderFind.setLayout(pnlOrderFindLayout);
        pnlOrderFindLayout.setHorizontalGroup(
            pnlOrderFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderFindLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCampoBusqueda)
                    .addGroup(pnlOrderFindLayout.createSequentialGroup()
                        .addComponent(lblCampoBusqueda)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlOrderFindLayout.createSequentialGroup()
                        .addGroup(pnlOrderFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radFindNroCliente)
                            .addComponent(radFindNroOrden))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFindOrder))
                    .addComponent(pnlEstadoOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlOrderFindLayout.setVerticalGroup(
            pnlOrderFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderFindLayout.createSequentialGroup()
                .addComponent(lblCampoBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCampoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnlOrderFindLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlOrderFindLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radFindNroCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(radFindNroOrden))
                    .addGroup(pnlOrderFindLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(btnFindOrder)
                        .addGap(11, 11, 11)))
                .addComponent(pnlEstadoOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlOrderListCriteria.setBorder(javax.swing.BorderFactory.createTitledBorder("Criterios de Ordenamiento"));

        btnGroupRadOrder.add(radCriteriaNroOrden);
        radCriteriaNroOrden.setSelected(true);
        radCriteriaNroOrden.setText("Nro Orden");
        radCriteriaNroOrden.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radCriteriaNroOrdenItemStateChanged(evt);
            }
        });

        btnGroupRadOrder.add(radCriteriaEstadoOrden);
        radCriteriaEstadoOrden.setText("Estado Orden");
        radCriteriaEstadoOrden.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radCriteriaEstadoOrdenItemStateChanged(evt);
            }
        });

        btnGroupRadOrder.add(radCriteriaFechaCreacion);
        radCriteriaFechaCreacion.setText("Fecha Creacion");
        radCriteriaFechaCreacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radCriteriaFechaCreacionItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout pnlOrderListCriteriaLayout = new javax.swing.GroupLayout(pnlOrderListCriteria);
        pnlOrderListCriteria.setLayout(pnlOrderListCriteriaLayout);
        pnlOrderListCriteriaLayout.setHorizontalGroup(
            pnlOrderListCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderListCriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOrderListCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radCriteriaNroOrden)
                    .addComponent(radCriteriaEstadoOrden)
                    .addComponent(radCriteriaFechaCreacion))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlOrderListCriteriaLayout.setVerticalGroup(
            pnlOrderListCriteriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOrderListCriteriaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radCriteriaNroOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radCriteriaEstadoOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radCriteriaFechaCreacion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlHigherFunctions.setBorder(javax.swing.BorderFactory.createTitledBorder("Otras Funciones"));

        btnNuevaOrden.setText("Crear Nueva Orden");
        btnNuevaOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaOrdenActionPerformed(evt);
            }
        });

        btnAbmItem.setText("Añadir Item");
        btnAbmItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbmItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlHigherFunctionsLayout = new javax.swing.GroupLayout(pnlHigherFunctions);
        pnlHigherFunctions.setLayout(pnlHigherFunctionsLayout);
        pnlHigherFunctionsLayout.setHorizontalGroup(
            pnlHigherFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHigherFunctionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHigherFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNuevaOrden, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAbmItem, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlHigherFunctionsLayout.setVerticalGroup(
            pnlHigherFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHigherFunctionsLayout.createSequentialGroup()
                .addComponent(btnNuevaOrden)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAbmItem))
        );

        javax.swing.GroupLayout pnlFunctionsLayout = new javax.swing.GroupLayout(pnlFunctions);
        pnlFunctions.setLayout(pnlFunctionsLayout);
        pnlFunctionsLayout.setHorizontalGroup(
            pnlFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFunctionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlOrderFind, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlOrderListCriteria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlHigherFunctions, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFunctionsLayout.setVerticalGroup(
            pnlFunctionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFunctionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlOrderFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlOrderListCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlHigherFunctions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlFunctions, java.awt.BorderLayout.LINE_START);

        tblOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblOrdersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblOrders);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Opciones");
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevaOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaOrdenActionPerformed
        // TODO add your handling code here:
//        CreateOrder wizard = new CreateOrder();
//        wizard.main();
        
        CreateNewOrder window = new CreateNewOrder();
        window.setVisible(true);
    }//GEN-LAST:event_btnNuevaOrdenActionPerformed

    private void btnAbmItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbmItemActionPerformed
        ABMItems items = new ABMItems();
        items.setVisible(true);
        
    }//GEN-LAST:event_btnAbmItemActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        initOrderTable();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tblOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblOrdersMouseClicked
        JTable input = (JTable) evt.getSource();

        Object inputKey = input.getValueAt(input.getSelectedRow(),
                0);

        if (inputKey != null) {
            Integer integer = (Integer) inputKey;

            List<Order> result = OrderFacadeSubject.getInstance().orderNumberSearch(integer);

            if (result.size() > 0) {
                OrderDetailWindow window = new OrderDetailWindow();
                window.order(result.get(0));
                window.setVisible(true);
            }
        }
    }//GEN-LAST:event_tblOrdersMouseClicked

    private void btnCargarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarDatosActionPerformed

        try {
            OrderFacadeSubject.getInstance().deSerialize(); //OrderFacadeSubject.getInstance().getRawPersistence();
            initOrderTable();
        } catch (IllegalAccessException | InvocationTargetException | IOException | InstantiationException | NoSuchMethodException | ClassNotFoundException ex) {
            try {
                OrderFacadeSubject.getInstance().deSerialize(); //OrderFacadeSubject.getInstance().getRawPersistence();
                initOrderTable();
            } catch (IllegalAccessException | InvocationTargetException | IOException | InstantiationException | NoSuchMethodException | ClassNotFoundException ex1) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al leer datos", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCargarDatosActionPerformed

    private void btnGuardarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDatosActionPerformed
        try {
            OrderFacadeSubject.getInstance().serialize();
            OrderFacadeSubject.getInstance().rawPersistence();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Error al grabar datos", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarDatosActionPerformed

    private void btnFindOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindOrderActionPerformed
        if (radFindNroOrden.isSelected()) {
            try {
                System.out.println("asdsadasd");
                List<Order> result = OrderFacadeSubject.getInstance().orderNumberSearch(new Integer(this.txtCampoBusqueda.getText()));
                OrderDataModel m = new OrderDataModel(result);
                this.tblOrders.setModel(m);
            } catch (NumberFormatException es) {
                JOptionPane.showMessageDialog(this, "El dato ingresado no es un numero", "Error al buscar", JOptionPane.WARNING_MESSAGE);
                txtCampoBusqueda.selectAll();
            }
        }

        if (radFindNroCliente.isSelected()) {
            try {
                List<Order> result = OrderFacadeSubject.getInstance().cltNmbSearch(new Integer(this.txtCampoBusqueda.getText()));
                OrderDataModel m = new OrderDataModel(result);
                this.tblOrders.setModel(m);
            } catch (NumberFormatException es) {
                JOptionPane.showMessageDialog(this, "El dato ingresado no es un numero", "Error al buscar", JOptionPane.WARNING_MESSAGE);
                txtCampoBusqueda.selectAll();
            }
        }

        if (radFindState.isSelected()) {
            List<Order> result = OrderFacadeSubject.getInstance().dispatchCenterSearch((String) cmbDispatcher.getSelectedItem());
                OrderDataModel m = new OrderDataModel(result);
                this.tblOrders.setModel(m);
        }

    }//GEN-LAST:event_btnFindOrderActionPerformed

    private void radCriteriaNroOrdenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radCriteriaNroOrdenItemStateChanged
        if (radCriteriaNroOrden.isSelected()) {
            OrderFacadeSubject.getInstance().setStrategy(new OrderIdListing(ListingStrategy.DESC));
            OrderDataModel model;
            model = new OrderDataModel(OrderFacadeSubject.getInstance().getOrderList());
        }
    }//GEN-LAST:event_radCriteriaNroOrdenItemStateChanged

    private void radCriteriaEstadoOrdenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radCriteriaEstadoOrdenItemStateChanged
        if (radCriteriaEstadoOrden.isSelected()) {
            OrderFacadeSubject.getInstance().setStrategy(new OrderStateListing(ListingStrategy.DESC));
            OrderDataModel model;
            model = new OrderDataModel(OrderFacadeSubject.getInstance().getOrderList());
        }
    }//GEN-LAST:event_radCriteriaEstadoOrdenItemStateChanged

    private void radCriteriaFechaCreacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radCriteriaFechaCreacionItemStateChanged
        if(radCriteriaFechaCreacion.isSelected()){
            OrderFacadeSubject.getInstance().setStrategy(new OrderDateListing(ListingStrategy.DESC));
            OrderDataModel model;
            model = new OrderDataModel(OrderFacadeSubject.getInstance().getOrderList());
        }
    }//GEN-LAST:event_radCriteriaFechaCreacionItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(
                    UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | UnsupportedLookAndFeelException | IllegalAccessException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
                    "Error cargando UI", JOptionPane.ERROR_MESSAGE);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbmItem;
    private javax.swing.JButton btnCargarDatos;
    private javax.swing.JButton btnFindOrder;
    private javax.swing.ButtonGroup btnGroupRadFind;
    private javax.swing.ButtonGroup btnGroupRadOrder;
    private javax.swing.JButton btnGuardarDatos;
    private javax.swing.JButton btnNuevaOrden;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JComboBox cmbDispatcher;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCampoBusqueda;
    private javax.swing.JPanel pnlEstadoOrden;
    private javax.swing.JPanel pnlFooter;
    private javax.swing.JPanel pnlFunctions;
    private javax.swing.JPanel pnlHigherFunctions;
    private javax.swing.JPanel pnlOrderFind;
    private javax.swing.JPanel pnlOrderListCriteria;
    private javax.swing.JPanel pnlTasks;
    private javax.swing.JRadioButton radCriteriaEstadoOrden;
    private javax.swing.JRadioButton radCriteriaFechaCreacion;
    private javax.swing.JRadioButton radCriteriaNroOrden;
    private javax.swing.JRadioButton radFindNroCliente;
    private javax.swing.JRadioButton radFindNroOrden;
    private javax.swing.JRadioButton radFindState;
    private javax.swing.JTable tblOrders;
    private javax.swing.JTextField txtCampoBusqueda;
    // End of variables declaration//GEN-END:variables
}
